# Generated by Django 3.2.20 on 2023-07-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0036_assignedproductattributevalue_product_data_migration"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="attributeproduct",
            name="assigned_products",
        ),
        migrations.RemoveField(
            model_name="assignedproductattributevalue",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="AssignedProductAttribute",
        ),
        migrations.AlterUniqueTogether(
            name="assignedproductattributevalue",
            unique_together={("value", "product")},
        ),
    ]

    operations = [
        # fill in data that was previously done in a celery task
        migrations.RunSQL(
            """
            UPDATE attribute_assignedproductattributevalue
            SET product_id = (
                SELECT product_id
                FROM attribute_assignedproductattribute
                WHERE attribute_assignedproductattributevalue.assignment_id = attribute_assignedproductattribute.id
            )
            WHERE id IN (
                SELECT ID FROM attribute_assignedproductattributevalue
                WHERE product_id IS NULL
                ORDER BY ID DESC
                FOR UPDATE
            );
            """,  # noqa
        ),
        # Set FKs to allow null values before marking their models/fields deleted
        migrations.AlterField(
            model_name="assignedproductattributevalue",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productvalueassignment",
                to="attribute.AssignedProductAttribute",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignedproductattribute",
            unique_together={},
        ),
        migrations.AlterField(
            model_name="assignedproductattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="product.Product",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignedproductattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productassignments",
                to="attribute.AttributeProduct",
                null=True,
            ),
        ),
        # Remove FK constraints so that the DB doesn't try to truncate the references
        migrations.RunSQL(
            """
            ALTER TABLE attribute_assignedproductattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpr_assignment_id_f65ddd91_fk_attribute;


            ALTER TABLE attribute_assignedproductattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpr_product_id_c267932a_fk_product_p;


            ALTER TABLE attribute_assignedproductattributevalue
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpa_assignment_id_6863be0a_fk_attribute
            """
        ),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
